let host = 'https://api.guapi.com.au/mobile' // 请求API地址
// let host = '/api/mobile' // 测试地址
let api = {
  url: 'https://api.guapi.com.au/', // 图片拼接地址
  base64Image: `${host}/base/base64Image`, // 上传图片
  top_base64Image: `${host}/base/top_base64Image`, // 上传图片(返回完整路径)
  getCode: `${host}/user/getCode`, // 发送验证码
  reg: `${host}/user/reg`, // 注册
  regs: `${host}/user/regs`, // 绑定手机号
  login: `${host}/user/login`, // 登录
  update_password: `${host}/user/update_password`, // 忘记密码
  h5_login: `${host}/user/h5_login`, // h5微信登录
  upload_id_cart: `${host}/index/upload_id_cart`, // 上传身份证
  province: `${host}/test/province`, // 身份证识别
  app_index: `${host}/index/app_index`, // 首页接口
  get_more: `${host}/index/get_more`, // 商品查看更多
  milk_goods: `${host}/index/milk_goods`, // 每日奶价
  get_three_good_lists: `${host}/index/get_three_good_lists`, // 首页三大模块
  get_good_lists: `${host}/good/get_good_lists`, // 全部商品
  get_caregory_brand: `${host}/good/get_caregory_brand`, // 全部商品分类和品牌筛选
  get_good_by_id: `${host}/good/get_good_by_id`, // 商品详情
  getShare: `${host}/user/getShare`, // 分享
  join_love: `${host}/good/join_love`, // 收藏商品
  cancele_love: `${host}/good/cancele_love`, // 取消收藏商品
  add_cart: `${host}/cart/add_cart`, // 加入购物车接口
  get_cart_list: `${host}/cart/get_cart_list`, // 购物车列表
  delete_cart: `${host}/cart/delete_cart`, // 删除购物车
  change_cart_num: `${host}/cart/change_cart_num`, // 购物车加减商品
  save_store_good_info: `${host}/store/save_store_good_info`, // 购物车门店自取信息保存接口
  commit_store: `${host}/store/commit_store`, // 提交门店自取
  save_mall_good_info: `${host}/store/save_mall_good_info`, // 购物车商城直发信息保存接口
  commit_mall: `${host}/store/commit_mall`, // 提交商城直发
  h5_commit_mall: `${host}/store/h5_commit_mall`, // 拖拽拆分提交商城直发
  auto_mall_good_infos: `${host}/store/auto_mall_good_infos`, // 包裹拆分
  delete_bkg: `${host}/store/delete_bkg`, // 删除包裹
  add_bkg: `${host}/store/add_bkg`, // 添加包裹
  edit_bkgs_info: `${host}/store/edit_bkgs_info`, // 编辑包裹
  delete_good_to_bkgs: `${host}/store/delete_good_to_bkgs`, // 删除包裹商品
  add_good_to_bkgs: `${host}/store/add_good_to_bkgs`, // 移动商品到指定包裹
  import_recipet_to_bkgs: `${host}/store/import_recipet_to_bkgs`, // 包裹导入收件组
  replace_recipet_to_bkg: `${host}/store/replace_recipet_to_bkg`, // 包裹导入单个收件人
  use_coupon: `${host}/user/use_coupon`, // 应用优惠代码
  get_sender_lists: `${host}/group/get_sender_lists`, // 发件人列表
  save_warehouse_good_info: `${host}/store/save_warehouse_good_info`, // 购物车提交云仓
  commit_cloud: `${host}/store/commit_cloud`, // 结算放入云仓
  user_info: `${host}/user/user_info`, // 会员资料信息
  get_favorite_good: `${host}/order/get_favorite_good`, // 收藏商品列表
  members_sign: `${host}/user/members_sign`, // 会员签到
  user_material: `${host}/user/user_material`, // 会员资料
  update_user_material: `${host}/user/update_user_material`, // 修改会员资料
  chmod_password: `${host}/user/chmod_password`, // 会员修改密码
  my_cloud_goods: `${host}/cloud/my_cloud_goods`, // 我的云仓
  my_cloud_goods_list: `${host}/cloud/my_cloud_goods_list`, // 操作云仓页面
  save_opera_cloud_info: `${host}/cloud/save_opera_cloud_info`, // 操作云仓信息保存接口
  save_opera_clouds: `${host}/cloud/save_opera_clouds`, // 提交操作云仓接口
  auto_opera_cloud_infos: `${host}/cloud/auto_opera_cloud_infos`, // 操作云仓拖拽拆分
  pay_cloud: `${host}/pay/pay_cloud`, // 云仓订单支付
  get_last: `${host}/user/get_last`, // 我的积分之受邀好友
  get_commisson: `${host}/user/get_commisson`, // 我的积分之佣金流水
  shares: `${host}/user/shares`, // 推广链接
  get_recipt_list: `${host}/group/get_recipt_list`, // 收件人库
  add_receipt: `${host}/group/add_receipt`, // 添加收件人
  get_recipt_lists: `${host}/group/get_recipt_lists`, // 导入收件人
  delete_receipt: `${host}/group/delete_receipt`, // 删除收件人
  get_recipt_info: `${host}/group/get_recipt_info`, // 收件人信息
  set_default: `${host}/group/set_default`, // 设置默认收件人
  update_receipt: `${host}/group/update_receipt`, // 修改收件人
  receipt_group_list: `${host}/group/receipt_group_list`, // 收件人组
  get_recipt_group_info: `${host}/group/get_recipt_group_info`, // 收件人组信息
  update_receipt_group: `${host}/group/update_receipt_group`, // 编辑收件人组信息
  set_default_group: `${host}/group/set_default_group`, // 设置默认收件人组
  delete_receipt_group: `${host}/group/delete_receipt_group`, // 删除收件人组
  add_receipt_group: `${host}/group/add_receipt_group`, // 添加收件人组接口
  get_sender_list: `${host}/group/get_sender_list`, // 发件人库
  set_default_sender: `${host}/group/set_default_sender`, // 设置默认发件人
  get_sender_Info: `${host}/group/get_sender_Info`, // 查看发件人信息
  delete_sender: `${host}/group/delete_sender`, // 删除发件人
  update_sender: `${host}/group/update_sender`, // 编辑发件人
  add_sender: `${host}/group/add_sender`, // 添加发件人接口
  recharge: `${host}/pay/recharge`, // 余额充值
  tantrer: `${host}/pay/tantrer`, // 余额充值澳洲转账
  my_cloud_log: `${host}/cloud/my_cloud_log`, // 云仓日志
  get_blance_log: `${host}/user/get_blance_log`, // 余额日志
  get_integral_log: `${host}/user/get_integral_log`, // 积分日志
  help: `${host}/index/help`, // 帮助中心
  help_detail: `${host}/index/help_detail`, // 帮助详情
  get_cloud_orders_lists: `${host}/cloud/get_cloud_orders_lists`, // 订单---云仓订单
  cancele_cloud_order: `${host}/cloud/cancele_cloud_order`, // 订单---云仓取消订单
  get_cloud_order_detail: `${host}/cloud/get_cloud_order_detail`, // 订单---云仓订单详情
  at_once_pay: `${host}/cloud/at_once_pay`, // 订单---云仓订单详情立即付款
  get_order_list: `${host}/order/get_order_list`, // 订单---商城订单
  order_detail: `${host}/order/order_detail`, // 订单---商城订单详情
  cancele_order: `${host}/order/cancele_order`, // 订单---商城取消订单
  pay_orders: `${host}/pay/pay_orders`, // 商城订单支付
  wex_pay_callback: `${host}/pay/wex_pay_callback`, // 小程序商城订单支付回调接口
  wex_pay: `${host}/pay/wex_pay`, // 小程序商城订单支付接口
  pay_clouds: `${host}/pay/pay_clouds`, // 云仓订单支付
  wx_play_cloud_callback: `${host}/pay/wx_play_cloud_callback`, // 小程序云仓订单支付回调接口
  wx_play_cloud: `${host}/pay/wx_play_cloud` // 小程序云仓订单支付接口
}
export default api
